### PR TITLE
Use rustfmt's defaults.

### PR DESCRIPTION
**Pull request by ltratt**
Clinging on to custom settings probably doesn't make sense any more.

### CODE REVIEW

**Review by ptersilie — APPROVED** [review]

**Comment by ptersilie** [comment]
Hah, didn't realise this wasn't on bors.

**Comment by ptersilie** [comment]
Still, something is off with travis.

**Comment by ltratt** [comment]
If you want to move this to bors, feel free; otherwise you can check it locally? I no longer remember how to use Travis :/

**Comment by vext01** [comment]
Just move the repo to our own CI and be done with it :P

**Comment by ptersilie** [comment]
Yes, I'd rather move this to bors than dealing with fixing travis.

**Comment by ptersilie** [comment]
On second thought (and after reading the instructions on how to add a project to bors), given that this repo is not gonna see much action it doesn't seem worth switching to bors. I've kicked travis instead, which fixed the problem.

**Pull request merged**
